// File generated by flutterfire configure
// This is a placeholder - run `flutterfire configure` to generate actual values

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] to use if no Firebase app is initialized.
///
/// Replace these values with ones generated by `flutterfire configure`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByndk7ngFb83xuaMazSAm3tU6F23L2-vg',
    appId: '1:343448345698:android:9ce4e22dccafcd0ec5853b',
    messagingSenderId: '343448345698',
    projectId: 'petpal-dc596',
    storageBucket: 'petpal-dc596.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx6h2AVuJ-M4oEbh367zzT1BPApnjVV7A',
    appId: '1:343448345698:ios:5147ef53c97e0a1ac5853b',
    messagingSenderId: '343448345698',
    projectId: 'petpal-dc596',
    storageBucket: 'petpal-dc596.firebasestorage.app',
    iosBundleId: 'com.petpal.app',
    iosClientId: '343448345698-3ihmdji017u32ti5pbkr74ojbe204957.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx6h2AVuJ-M4oEbh367zzT1BPApnjVV7A',
    appId: '1:343448345698:ios:5147ef53c97e0a1ac5853b',
    messagingSenderId: '343448345698',
    projectId: 'petpal-dc596',
    storageBucket: 'petpal-dc596.firebasestorage.app',
    iosBundleId: 'com.petpal.app.macos',
    iosClientId: '343448345698-3ihmdji017u32ti5pbkr74ojbe204957.apps.googleusercontent.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyClK-yD-MhsmrxvpwftcZqnbFLTZmotRWM",
    authDomain: "petpal-dc596.firebaseapp.com",
    projectId: "petpal-dc596",
    storageBucket: "petpal-dc596.firebasestorage.app",
    messagingSenderId: "343448345698",
    appId: "1:343448345698:web:c50aece17ade91b8c5853b",
    measurementId: "G-QNT8GCF0EM",
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyClK-yD-MhsmrxvpwftcZqnbFLTZmotRWM',
    authDomain: 'petpal-dc596.firebaseapp.com',
    projectId: 'petpal-dc596',
    storageBucket: 'petpal-dc596.firebasestorage.app',
    messagingSenderId: '343448345698',
    appId: '1:343448345698:web:c50aece17ade91b8c5853b',
    measurementId: 'G-QNT8GCF0EM',
  );
}

