import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Placeholder Firebase configuration.
///
/// Replace the [FirebaseOptions] values with the ones generated by
/// `flutterfire configure` for each available platform.
class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'ADD_ANDROID_API_KEY',
    appId: 'ADD_ANDROID_APP_ID',
    messagingSenderId: 'ADD_SENDER_ID',
    projectId: 'ADD_PROJECT_ID',
    storageBucket: 'ADD_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'ADD_IOS_API_KEY',
    appId: 'ADD_IOS_APP_ID',
    messagingSenderId: 'ADD_SENDER_ID',
    projectId: 'ADD_PROJECT_ID',
    storageBucket: 'ADD_STORAGE_BUCKET',
    iosClientId: 'ADD_IOS_CLIENT_ID',
    iosBundleId: 'com.petpal.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'ADD_MACOS_API_KEY',
    appId: 'ADD_MACOS_APP_ID',
    messagingSenderId: 'ADD_SENDER_ID',
    projectId: 'ADD_PROJECT_ID',
    storageBucket: 'ADD_STORAGE_BUCKET',
    iosClientId: 'ADD_MACOS_CLIENT_ID',
    iosBundleId: 'com.petpal.app.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'ADD_WINDOWS_API_KEY',
    appId: 'ADD_WINDOWS_APP_ID',
    messagingSenderId: 'ADD_SENDER_ID',
    projectId: 'ADD_PROJECT_ID',
    storageBucket: 'ADD_STORAGE_BUCKET',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'ADD_LINUX_API_KEY',
    appId: 'ADD_LINUX_APP_ID',
    messagingSenderId: 'ADD_SENDER_ID',
    projectId: 'ADD_PROJECT_ID',
    storageBucket: 'ADD_STORAGE_BUCKET',
  );
}
